baseURL = 'https://blog.abin-tseng.com/'
languageCode = 'zh-tw'
title = "ABIN TSENG"
theme =  ["github.com/Mitrichius/hugo-theme-anubis"]
googleAnalytics = 'G-31KRXTHG3J'

[module]
[[module.imports]]
  path = 'github.com/hugomods/images'

[manu]
[[menu.main]]
  name = "All Posts"
  pageRef = "/posts"
  weight = 1
[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 0
[[menu.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 10

[params]
author = "ABIN TSENG"
description = "Backend Developer"
rssAsSocialIcon = 'true'

customCSS = [ "css/my.css" ]
style = "dark-without-switcher"

utterancesRepo = "AaaBin/blog_reply"
utterancesTheme = "gruvbox-dark"
utterancesIssue = "pathname"
utterancesLabel = "blog-comment"

[params.images]
    modern_format = 'webp'

# RSS
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
languageCode = 'zh-tw'
[author]
  name = 'Abin Tseng'

